import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { createTheme, MantineProvider } from "@mantine/core";

import "@mantine/core/styles.css";
import "@rainbow-me/rainbowkit/styles.css";
import { Provider } from "./provider";

const theme = createTheme({});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <Provider>{children}</Provider>
        </MantineProvider>
      </body>
    </html>
  );
}
